/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Function;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Numbers;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl#getElement <em>Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl#getNumb1 <em>Numb1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl#getNumb2 <em>Numb2</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class FunctionImpl extends MinimalEObjectImpl.Container implements Function
{
  /**
   * The default value of the '{@link #getElement() <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElement()
   * @generated
   * @ordered
   */
  protected static final String ELEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getElement() <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElement()
   * @generated
   * @ordered
   */
  protected String element = ELEMENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getNumb1() <em>Numb1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumb1()
   * @generated
   * @ordered
   */
  protected Numbers numb1;

  /**
   * The cached value of the '{@link #getNumb2() <em>Numb2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumb2()
   * @generated
   * @ordered
   */
  protected Numbers numb2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getElement()
  {
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElement(String newElement)
  {
    String oldElement = element;
    element = newElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FUNCTION__ELEMENT, oldElement, element));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Numbers getNumb1()
  {
    return numb1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNumb1(Numbers newNumb1, NotificationChain msgs)
  {
    Numbers oldNumb1 = numb1;
    numb1 = newNumb1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FUNCTION__NUMB1, oldNumb1, newNumb1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNumb1(Numbers newNumb1)
  {
    if (newNumb1 != numb1)
    {
      NotificationChain msgs = null;
      if (numb1 != null)
        msgs = ((InternalEObject)numb1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUNCTION__NUMB1, null, msgs);
      if (newNumb1 != null)
        msgs = ((InternalEObject)newNumb1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUNCTION__NUMB1, null, msgs);
      msgs = basicSetNumb1(newNumb1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FUNCTION__NUMB1, newNumb1, newNumb1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Numbers getNumb2()
  {
    return numb2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNumb2(Numbers newNumb2, NotificationChain msgs)
  {
    Numbers oldNumb2 = numb2;
    numb2 = newNumb2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.FUNCTION__NUMB2, oldNumb2, newNumb2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNumb2(Numbers newNumb2)
  {
    if (newNumb2 != numb2)
    {
      NotificationChain msgs = null;
      if (numb2 != null)
        msgs = ((InternalEObject)numb2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUNCTION__NUMB2, null, msgs);
      if (newNumb2 != null)
        msgs = ((InternalEObject)newNumb2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.FUNCTION__NUMB2, null, msgs);
      msgs = basicSetNumb2(newNumb2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FUNCTION__NUMB2, newNumb2, newNumb2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION__NUMB1:
        return basicSetNumb1(null, msgs);
      case MyDslPackage.FUNCTION__NUMB2:
        return basicSetNumb2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION__ELEMENT:
        return getElement();
      case MyDslPackage.FUNCTION__NUMB1:
        return getNumb1();
      case MyDslPackage.FUNCTION__NUMB2:
        return getNumb2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION__ELEMENT:
        setElement((String)newValue);
        return;
      case MyDslPackage.FUNCTION__NUMB1:
        setNumb1((Numbers)newValue);
        return;
      case MyDslPackage.FUNCTION__NUMB2:
        setNumb2((Numbers)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION__ELEMENT:
        setElement(ELEMENT_EDEFAULT);
        return;
      case MyDslPackage.FUNCTION__NUMB1:
        setNumb1((Numbers)null);
        return;
      case MyDslPackage.FUNCTION__NUMB2:
        setNumb2((Numbers)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FUNCTION__ELEMENT:
        return ELEMENT_EDEFAULT == null ? element != null : !ELEMENT_EDEFAULT.equals(element);
      case MyDslPackage.FUNCTION__NUMB1:
        return numb1 != null;
      case MyDslPackage.FUNCTION__NUMB2:
        return numb2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (element: ");
    result.append(element);
    result.append(')');
    return result.toString();
  }

} //FunctionImpl
