/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ADD</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ADD#getAdd2 <em>Add2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getADD()
 * @model
 * @generated
 */
public interface ADD extends EObject
{
  /**
   * Returns the value of the '<em><b>Add2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Add2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add2</em>' attribute.
   * @see #setAdd2(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getADD_Add2()
   * @model
   * @generated
   */
  String getAdd2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ADD#getAdd2 <em>Add2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add2</em>' attribute.
   * @see #getAdd2()
   * @generated
   */
  void setAdd2(String value);

} // ADD
