/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Expression#getComplement <em>Complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Expression#getConcat <em>Concat</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complement</em>' containment reference.
   * @see #setComplement(Complement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Complement()
   * @model containment="true"
   * @generated
   */
  Complement getComplement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Expression#getComplement <em>Complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complement</em>' containment reference.
   * @see #getComplement()
   * @generated
   */
  void setComplement(Complement value);

  /**
   * Returns the value of the '<em><b>Concat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concat</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concat</em>' containment reference.
   * @see #setConcat(Concat)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Concat()
   * @model containment="true"
   * @generated
   */
  Concat getConcat();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Expression#getConcat <em>Concat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concat</em>' containment reference.
   * @see #getConcat()
   * @generated
   */
  void setConcat(Concat value);

} // Expression
