/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Function#getElement <em>Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Function#getNumb1 <em>Numb1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Function#getNumb2 <em>Numb2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' attribute.
   * @see #setElement(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFunction_Element()
   * @model
   * @generated
   */
  String getElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Function#getElement <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' attribute.
   * @see #getElement()
   * @generated
   */
  void setElement(String value);

  /**
   * Returns the value of the '<em><b>Numb1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numb1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numb1</em>' containment reference.
   * @see #setNumb1(Numbers)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFunction_Numb1()
   * @model containment="true"
   * @generated
   */
  Numbers getNumb1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Function#getNumb1 <em>Numb1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numb1</em>' containment reference.
   * @see #getNumb1()
   * @generated
   */
  void setNumb1(Numbers value);

  /**
   * Returns the value of the '<em><b>Numb2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numb2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numb2</em>' containment reference.
   * @see #setNumb2(Numbers)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFunction_Numb2()
   * @model containment="true"
   * @generated
   */
  Numbers getNumb2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Function#getNumb2 <em>Numb2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numb2</em>' containment reference.
   * @see #getNumb2()
   * @generated
   */
  void setNumb2(Numbers value);

} // Function
