/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>INSIDE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.INSIDE#getInside2 <em>Inside2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getINSIDE()
 * @model
 * @generated
 */
public interface INSIDE extends EObject
{
  /**
   * Returns the value of the '<em><b>Inside2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inside2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inside2</em>' attribute.
   * @see #setInside2(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getINSIDE_Inside2()
   * @model
   * @generated
   */
  String getInside2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.INSIDE#getInside2 <em>Inside2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inside2</em>' attribute.
   * @see #getInside2()
   * @generated
   */
  void setInside2(String value);

} // INSIDE
