/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Haskell</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__HASKELL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.HaskellImpl <em>Haskell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.HaskellImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHaskell()
   * @generated
   */
  int HASKELL = 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASKELL__EXPRESSION = 0;

  /**
   * The number of structural features of the '<em>Haskell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HASKELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The feature id for the '<em><b>Complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__COMPLEMENT = 0;

  /**
   * The feature id for the '<em><b>Concat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__CONCAT = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FunctionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Numb1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NUMB1 = 1;

  /**
   * The feature id for the '<em><b>Numb2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NUMB2 = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComplementImpl <em>Complement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComplementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComplement()
   * @generated
   */
  int COMPLEMENT = 3;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__ELEMENT = FUNCTION__ELEMENT;

  /**
   * The feature id for the '<em><b>Numb1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__NUMB1 = FUNCTION__NUMB1;

  /**
   * The feature id for the '<em><b>Numb2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__NUMB2 = FUNCTION__NUMB2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__ID = FUNCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Numbers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__NUMBERS = FUNCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__FUNCTION = FUNCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Complement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT_FEATURE_COUNT = FUNCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NumbersImpl <em>Numbers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NumbersImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNumbers()
   * @generated
   */
  int NUMBERS = 5;

  /**
   * The feature id for the '<em><b>One</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS__ONE = 0;

  /**
   * The feature id for the '<em><b>Numb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS__NUMB = 1;

  /**
   * The feature id for the '<em><b>Two</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS__TWO = 2;

  /**
   * The number of structural features of the '<em>Numbers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConcatImpl <em>Concat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConcatImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConcat()
   * @generated
   */
  int CONCAT = 6;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT__ID = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT__OP = 1;

  /**
   * The feature id for the '<em><b>New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT__NEW = 2;

  /**
   * The number of structural features of the '<em>Concat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCAT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NewConcatImpl <em>New Concat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NewConcatImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNewConcat()
   * @generated
   */
  int NEW_CONCAT = 7;

  /**
   * The feature id for the '<em><b>Haskell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_CONCAT__HASKELL = 0;

  /**
   * The number of structural features of the '<em>New Concat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_CONCAT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getHaskell <em>Haskell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Haskell</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getHaskell()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Haskell();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Haskell <em>Haskell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Haskell</em>'.
   * @see org.xtext.example.mydsl.myDsl.Haskell
   * @generated
   */
  EClass getHaskell();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Haskell#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.Haskell#getExpression()
   * @see #getHaskell()
   * @generated
   */
  EReference getHaskell_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Expression#getComplement <em>Complement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Complement</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression#getComplement()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Complement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Expression#getConcat <em>Concat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Concat</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression#getConcat()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Concat();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Complement <em>Complement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complement</em>'.
   * @see org.xtext.example.mydsl.myDsl.Complement
   * @generated
   */
  EClass getComplement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Complement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Complement#getId()
   * @see #getComplement()
   * @generated
   */
  EAttribute getComplement_Id();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Complement#getNumbers <em>Numbers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Numbers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Complement#getNumbers()
   * @see #getComplement()
   * @generated
   */
  EReference getComplement_Numbers();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Complement#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.Complement#getFunction()
   * @see #getComplement()
   * @generated
   */
  EReference getComplement_Function();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Function#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getElement()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Element();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Function#getNumb1 <em>Numb1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Numb1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getNumb1()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Numb1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Function#getNumb2 <em>Numb2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Numb2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Function#getNumb2()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Numb2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Numbers <em>Numbers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numbers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Numbers
   * @generated
   */
  EClass getNumbers();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Numbers#getOne <em>One</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>One</em>'.
   * @see org.xtext.example.mydsl.myDsl.Numbers#getOne()
   * @see #getNumbers()
   * @generated
   */
  EAttribute getNumbers_One();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Numbers#getNumb <em>Numb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Numb</em>'.
   * @see org.xtext.example.mydsl.myDsl.Numbers#getNumb()
   * @see #getNumbers()
   * @generated
   */
  EReference getNumbers_Numb();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Numbers#getTwo <em>Two</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Two</em>'.
   * @see org.xtext.example.mydsl.myDsl.Numbers#getTwo()
   * @see #getNumbers()
   * @generated
   */
  EAttribute getNumbers_Two();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Concat <em>Concat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concat</em>'.
   * @see org.xtext.example.mydsl.myDsl.Concat
   * @generated
   */
  EClass getConcat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Concat#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Concat#getId()
   * @see #getConcat()
   * @generated
   */
  EAttribute getConcat_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Concat#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.Concat#getOp()
   * @see #getConcat()
   * @generated
   */
  EAttribute getConcat_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Concat#getNew <em>New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>New</em>'.
   * @see org.xtext.example.mydsl.myDsl.Concat#getNew()
   * @see #getConcat()
   * @generated
   */
  EReference getConcat_New();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NewConcat <em>New Concat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Concat</em>'.
   * @see org.xtext.example.mydsl.myDsl.NewConcat
   * @generated
   */
  EClass getNewConcat();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.NewConcat#getHaskell <em>Haskell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Haskell</em>'.
   * @see org.xtext.example.mydsl.myDsl.NewConcat#getHaskell()
   * @see #getNewConcat()
   * @generated
   */
  EReference getNewConcat_Haskell();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Haskell</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__HASKELL = eINSTANCE.getModel_Haskell();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.HaskellImpl <em>Haskell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.HaskellImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHaskell()
     * @generated
     */
    EClass HASKELL = eINSTANCE.getHaskell();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HASKELL__EXPRESSION = eINSTANCE.getHaskell_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Complement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__COMPLEMENT = eINSTANCE.getExpression_Complement();

    /**
     * The meta object literal for the '<em><b>Concat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__CONCAT = eINSTANCE.getExpression_Concat();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComplementImpl <em>Complement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComplementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComplement()
     * @generated
     */
    EClass COMPLEMENT = eINSTANCE.getComplement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEMENT__ID = eINSTANCE.getComplement_Id();

    /**
     * The meta object literal for the '<em><b>Numbers</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEMENT__NUMBERS = eINSTANCE.getComplement_Numbers();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEMENT__FUNCTION = eINSTANCE.getComplement_Function();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FunctionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__ELEMENT = eINSTANCE.getFunction_Element();

    /**
     * The meta object literal for the '<em><b>Numb1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__NUMB1 = eINSTANCE.getFunction_Numb1();

    /**
     * The meta object literal for the '<em><b>Numb2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__NUMB2 = eINSTANCE.getFunction_Numb2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NumbersImpl <em>Numbers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NumbersImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNumbers()
     * @generated
     */
    EClass NUMBERS = eINSTANCE.getNumbers();

    /**
     * The meta object literal for the '<em><b>One</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERS__ONE = eINSTANCE.getNumbers_One();

    /**
     * The meta object literal for the '<em><b>Numb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBERS__NUMB = eINSTANCE.getNumbers_Numb();

    /**
     * The meta object literal for the '<em><b>Two</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERS__TWO = eINSTANCE.getNumbers_Two();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConcatImpl <em>Concat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConcatImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getConcat()
     * @generated
     */
    EClass CONCAT = eINSTANCE.getConcat();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCAT__ID = eINSTANCE.getConcat_Id();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCAT__OP = eINSTANCE.getConcat_Op();

    /**
     * The meta object literal for the '<em><b>New</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCAT__NEW = eINSTANCE.getConcat_New();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NewConcatImpl <em>New Concat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NewConcatImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNewConcat()
     * @generated
     */
    EClass NEW_CONCAT = eINSTANCE.getNewConcat();

    /**
     * The meta object literal for the '<em><b>Haskell</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_CONCAT__HASKELL = eINSTANCE.getNewConcat_Haskell();

  }

} //MyDslPackage
