/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>N</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.N#getInteger <em>Integer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.N#getPrint <em>Print</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getN()
 * @model
 * @generated
 */
public interface N extends EObject
{
  /**
   * Returns the value of the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Integer</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer</em>' attribute.
   * @see #setInteger(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getN_Integer()
   * @model
   * @generated
   */
  String getInteger();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.N#getInteger <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer</em>' attribute.
   * @see #getInteger()
   * @generated
   */
  void setInteger(String value);

  /**
   * Returns the value of the '<em><b>Print</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Print</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print</em>' attribute.
   * @see #setPrint(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getN_Print()
   * @model
   * @generated
   */
  String getPrint();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.N#getPrint <em>Print</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Print</em>' attribute.
   * @see #getPrint()
   * @generated
   */
  void setPrint(String value);

} // N
