/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Concat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NewConcat#getHaskell <em>Haskell</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNewConcat()
 * @model
 * @generated
 */
public interface NewConcat extends EObject
{
  /**
   * Returns the value of the '<em><b>Haskell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Haskell</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Haskell</em>' containment reference.
   * @see #setHaskell(Haskell)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNewConcat_Haskell()
   * @model containment="true"
   * @generated
   */
  Haskell getHaskell();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NewConcat#getHaskell <em>Haskell</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Haskell</em>' containment reference.
   * @see #getHaskell()
   * @generated
   */
  void setHaskell(Haskell value);

} // NewConcat
