/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numbers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Numbers#getOne <em>One</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Numbers#getNumb <em>Numb</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Numbers#getTwo <em>Two</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNumbers()
 * @model
 * @generated
 */
public interface Numbers extends EObject
{
  /**
   * Returns the value of the '<em><b>One</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>One</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>One</em>' attribute.
   * @see #setOne(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNumbers_One()
   * @model
   * @generated
   */
  int getOne();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Numbers#getOne <em>One</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>One</em>' attribute.
   * @see #getOne()
   * @generated
   */
  void setOne(int value);

  /**
   * Returns the value of the '<em><b>Numb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numb</em>' containment reference.
   * @see #setNumb(Numbers)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNumbers_Numb()
   * @model containment="true"
   * @generated
   */
  Numbers getNumb();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Numbers#getNumb <em>Numb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numb</em>' containment reference.
   * @see #getNumb()
   * @generated
   */
  void setNumb(Numbers value);

  /**
   * Returns the value of the '<em><b>Two</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Two</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Two</em>' attribute.
   * @see #setTwo(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNumbers_Two()
   * @model
   * @generated
   */
  int getTwo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Numbers#getTwo <em>Two</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Two</em>' attribute.
   * @see #getTwo()
   * @generated
   */
  void setTwo(int value);

} // Numbers
