/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OP#getInside <em>Inside</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOP()
 * @model
 * @generated
 */
public interface OP extends EObject
{
  /**
   * Returns the value of the '<em><b>Inside</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.INSIDE}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inside</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inside</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOP_Inside()
   * @model containment="true"
   * @generated
   */
  EList<INSIDE> getInside();

} // OP
