/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ZIP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ZIP#getOp2 <em>Op2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ZIP#getOp3 <em>Op3</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZIP()
 * @model
 * @generated
 */
public interface ZIP extends EObject
{
  /**
   * Returns the value of the '<em><b>Op2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op2</em>' containment reference.
   * @see #setOp2(OP)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZIP_Op2()
   * @model containment="true"
   * @generated
   */
  OP getOp2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ZIP#getOp2 <em>Op2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op2</em>' containment reference.
   * @see #getOp2()
   * @generated
   */
  void setOp2(OP value);

  /**
   * Returns the value of the '<em><b>Op3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op3</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op3</em>' containment reference.
   * @see #setOp3(OP)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZIP_Op3()
   * @model containment="true"
   * @generated
   */
  OP getOp3();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ZIP#getOp3 <em>Op3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op3</em>' containment reference.
   * @see #getOp3()
   * @generated
   */
  void setOp3(OP value);

} // ZIP
